services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JWeiland\Replacer\:
    resource: '../Classes/*'

  # Event Listener Configuration
  # This event listener is implemented for replacing the Hook implementation which is removed in TYPO3 12LTS
  # the implementation is same as the ReplaceContent Middleware (which only replace for USER_INT Plugins)
  JWeiland\Replacer\EventListener\CacheableContentGeneratedEventListener:
    tags:
      - name: event.listener
        identifier: 'replacer/content-modifier'
        event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent
